-- MySQL Script generated by MySQL Workbench
-- Tue 05 Feb 2019 08:00:04 PM +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema classOnline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema classOnline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `classOnline` DEFAULT CHARACTER SET utf8 ;
USE `classOnline` ;

-- -----------------------------------------------------
-- Table `classOnline`.`type_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`type_class` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `classOnline`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`class` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Type_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Class_Type1_idx` (`Type_id` ASC),
  CONSTRAINT `fk_Class_Type1`
    FOREIGN KEY (`Type_id`)
    REFERENCES `classOnline`.`type_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_german2_ci;


-- -----------------------------------------------------
-- Table `classOnline`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `facebook` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `classOnline`.`class_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`class_has_user` (
  `Class_id` INT(11) NOT NULL,
  `User_id` INT(11) NOT NULL,
  PRIMARY KEY (`Class_id`, `User_id`),
  INDEX `fk_Class_has_User_User1_idx` (`User_id` ASC),
  INDEX `fk_Class_has_User_Class1_idx` (`Class_id` ASC),
  CONSTRAINT `fk_Class_has_User_Class1`
    FOREIGN KEY (`Class_id`)
    REFERENCES `classOnline`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Class_has_User_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `classOnline`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `classOnline`.`type_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`type_post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classOnline`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`Post` (
  `id` INT NOT NULL PRIMARY Key AUTO_INCREMENT,
  `Content` LONGTEXT NULL,
  `user_id` INT(11) NOT NULL,
  `type_post_id` INT NOT NULL,
  `Created` DATETIME NULL,
  `class_id` INT(11) ,
  INDEX `fk_Post_user1_idx` (`user_id` ASC),
  INDEX `fk_Post_type_post1_idx` (`type_post_id` ASC),
  INDEX `fk_Post_class1_idx` (`class_id` ASC),
  CONSTRAINT `fk_Post_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `classOnline`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_type_post1`
    FOREIGN KEY (`type_post_id`)
    REFERENCES `classOnline`.`type_post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `classOnline`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classOnline`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`data` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `location` VARCHAR(200) NULL DEFAULT NULL,
  `Post_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_data_Post1_idx` (`Post_id` ASC),
  CONSTRAINT `fk_data_Post1`
    FOREIGN KEY (`Post_id`)
    REFERENCES `classOnline`.`Post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `classOnline`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`login` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `User_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_login_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_login_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `classOnline`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `classOnline`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `classOnline`.`user_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`user_has_roles` (
  `User_id` INT(11) NOT NULL,
  `Roles_id` INT(11) NOT NULL,
  PRIMARY KEY (`User_id`, `Roles_id`),
  INDEX `fk_User_has_Roles_Roles1_idx` (`Roles_id` ASC),
  INDEX `fk_User_has_Roles_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_User_has_Roles_Roles1`
    FOREIGN KEY (`Roles_id`)
    REFERENCES `classOnline`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Roles_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `classOnline`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `classOnline`.`Post_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`Post_has_roles` (
  `Post_id` INT NOT NULL,
  `roles_id` INT(11) NOT NULL,
  PRIMARY KEY (`Post_id`, `roles_id`),
  INDEX `fk_Post_has_roles_roles1_idx` (`roles_id` ASC),
  INDEX `fk_Post_has_roles_Post1_idx` (`Post_id` ASC),
  CONSTRAINT `fk_Post_has_roles_Post1`
    FOREIGN KEY (`Post_id`)
    REFERENCES `classOnline`.`Post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_has_roles_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `classOnline`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classOnline`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`Comment` (
  `user_id` INT(11) NOT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Post_id` INT(11) NOT NULL,
  `Content` TEXT NULL,
  INDEX `fk_Comment_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_Comment_Post1_idx` (`Post_id` ASC),
  CONSTRAINT `fk_Comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `classOnline`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Post1`
    FOREIGN KEY (`Post_id`)
    REFERENCES `classOnline`.`Post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

