-- MySQL Script generated by MySQL Workbench
-- Mon 07 Jan 2019 02:12:30 AM +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema classOnline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema classOnline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `classOnline` DEFAULT CHARACTER SET latin1 ;
USE `classOnline` ;

-- -----------------------------------------------------
-- Table `classOnline`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classOnline`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`class` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `Type_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Class_Type1_idx` (`Type_id` ASC),
  CONSTRAINT `fk_Class_Type1`
    FOREIGN KEY (`Type_id`)
    REFERENCES `classOnline`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_german2_ci;


-- -----------------------------------------------------
-- Table `classOnline`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `facebook` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classOnline`.`class_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`class_has_user` (
  `Class_id` INT(11) NOT NULL,
  `User_id` INT(11) NOT NULL,
  PRIMARY KEY (`Class_id`, `User_id`),
  INDEX `fk_Class_has_User_User1_idx` (`User_id` ASC),
  INDEX `fk_Class_has_User_Class1_idx` (`Class_id` ASC),
  CONSTRAINT `fk_Class_has_User_Class1`
    FOREIGN KEY (`Class_id`)
    REFERENCES `classOnline`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Class_has_User_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `classOnline`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classOnline`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classOnline`.`user_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`user_has_roles` (
  `User_id` INT(11) NOT NULL,
  `Roles_id` INT(11) NOT NULL,
  PRIMARY KEY (`User_id`, `Roles_id`),
  INDEX `fk_User_has_Roles_Roles1_idx` (`Roles_id` ASC),
  INDEX `fk_User_has_Roles_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_User_has_Roles_Roles1`
    FOREIGN KEY (`Roles_id`)
    REFERENCES `classOnline`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Roles_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `classOnline`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classOnline`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `Class_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_group_Class1_idx` (`Class_id` ASC),
  CONSTRAINT `fk_group_Class1`
    FOREIGN KEY (`Class_id`)
    REFERENCES `classOnline`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classOnline`.`user_has_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`user_has_group` (
  `User_id` INT(11) NOT NULL,
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`User_id`, `group_id`),
  INDEX `fk_User_has_group_group1_idx` (`group_id` ASC),
  INDEX `fk_User_has_group_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_User_has_group_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `classOnline`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_group_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `classOnline`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classOnline`.`exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`exercise` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `content` VARCHAR(45) NULL DEFAULT NULL,
  `Class_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_exercise_Class1_idx` (`Class_id` ASC),
  CONSTRAINT `fk_exercise_Class1`
    FOREIGN KEY (`Class_id`)
    REFERENCES `classOnline`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classOnline`.`lab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`lab` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` MEDIUMTEXT NULL DEFAULT NULL,
  `title` MEDIUMTEXT NULL DEFAULT NULL,
  `score` INT(11) NULL DEFAULT '10',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classOnline`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`data` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `location` VARCHAR(200) NULL DEFAULT NULL,
  `exercise_id` INT(11) NOT NULL,
  `lab_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_data_exercise1_idx` (`exercise_id` ASC),
  INDEX `fk_data_lab1_idx` (`lab_id` ASC),
  CONSTRAINT `fk_data_exercise1`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `classOnline`.`exercise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_lab1`
    FOREIGN KEY (`lab_id`)
    REFERENCES `classOnline`.`lab` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classOnline`.`knex_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`knex_migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `batch` INT(11) NULL DEFAULT NULL,
  `migration_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classOnline`.`knex_migrations_lock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`knex_migrations_lock` (
  `index` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `is_locked` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`index`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classOnline`.`lab_has_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`lab_has_group` (
  `lab_id` INT(11) NOT NULL,
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`lab_id`, `group_id`),
  INDEX `fk_lab_has_group_group1_idx` (`group_id` ASC),
  INDEX `fk_lab_has_group_lab1_idx` (`lab_id` ASC),
  CONSTRAINT `fk_lab_has_group_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `classOnline`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lab_has_group_lab1`
    FOREIGN KEY (`lab_id`)
    REFERENCES `classOnline`.`lab` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classOnline`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`login` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `User_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_login_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_login_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `classOnline`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
