-- MySQL Script generated by MySQL Workbench
-- Sun 06 Jan 2019 10:38:02 PM +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema classOnline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema classOnline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `classOnline` DEFAULT CHARACTER SET utf8 ;
USE `classOnline` ;

-- -----------------------------------------------------
-- Table `classOnline`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`User` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `facebook` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classOnline`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`Type` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classOnline`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`Class` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `Type` VARCHAR(45) NULL,
  `Type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Class_Type1_idx` (`Type_id` ASC),
  CONSTRAINT `fk_Class_Type1`
    FOREIGN KEY (`Type_id`)
    REFERENCES `classOnline`.`Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classOnline`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`group` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `Class_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_group_Class1_idx` (`Class_id` ASC),
  CONSTRAINT `fk_group_Class1`
    FOREIGN KEY (`Class_id`)
    REFERENCES `classOnline`.`Class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classOnline`.`lab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`lab` (
  `id` INT NOT NULL,
  `content` MEDIUMTEXT NULL,
  `title` MEDIUMTEXT NULL,
  `score` INT NULL DEFAULT 10,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classOnline`.`exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`exercise` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `Class_id` INT NOT NULL,
  `Class_Type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_exercise_Class1_idx` (`Class_id` ASC, `Class_Type_id` ASC),
  CONSTRAINT `fk_exercise_Class1`
    FOREIGN KEY (`Class_id`)
    REFERENCES `classOnline`.`Class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classOnline`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`data` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `location` VARCHAR(200) NULL,
  `exercise_id` INT NOT NULL,
  `lab_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_data_exercise1_idx` (`exercise_id` ASC),
  INDEX `fk_data_lab1_idx` (`lab_id` ASC),
  CONSTRAINT `fk_data_exercise1`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `classOnline`.`exercise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_lab1`
    FOREIGN KEY (`lab_id`)
    REFERENCES `classOnline`.`lab` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classOnline`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`login` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_login_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_login_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `classOnline`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classOnline`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`Roles` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classOnline`.`User_has_Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`User_has_Roles` (
  `User_id` INT NOT NULL,
  `Roles_id` INT NOT NULL,
  PRIMARY KEY (`User_id`, `Roles_id`),
  INDEX `fk_User_has_Roles_Roles1_idx` (`Roles_id` ASC),
  INDEX `fk_User_has_Roles_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_User_has_Roles_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `classOnline`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Roles_Roles1`
    FOREIGN KEY (`Roles_id`)
    REFERENCES `classOnline`.`Roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classOnline`.`Class_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`Class_has_User` (
  `Class_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`Class_id`, `User_id`),
  INDEX `fk_Class_has_User_User1_idx` (`User_id` ASC),
  INDEX `fk_Class_has_User_Class1_idx` (`Class_id` ASC),
  CONSTRAINT `fk_Class_has_User_Class1`
    FOREIGN KEY (`Class_id`)
    REFERENCES `classOnline`.`Class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Class_has_User_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `classOnline`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classOnline`.`User_has_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`User_has_group` (
  `User_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`User_id`, `group_id`),
  INDEX `fk_User_has_group_group1_idx` (`group_id` ASC),
  INDEX `fk_User_has_group_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_User_has_group_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `classOnline`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_group_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `classOnline`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classOnline`.`lab_has_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classOnline`.`lab_has_group` (
  `lab_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`lab_id`, `group_id`),
  INDEX `fk_lab_has_group_group1_idx` (`group_id` ASC),
  INDEX `fk_lab_has_group_lab1_idx` (`lab_id` ASC),
  CONSTRAINT `fk_lab_has_group_lab1`
    FOREIGN KEY (`lab_id`)
    REFERENCES `classOnline`.`lab` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lab_has_group_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `classOnline`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
